[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@forge-std/=lib/forge-std/src/"
]

[profile.sepolia]
chain_id = 11155111

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/AFjoSzKjqv6Eq53OsF2xe"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
